# Used in Airflow DAG - Mind the differences between hosts
dbt_transformations_airflow:
  outputs:
    dev:
      type: postgres
      threads: 1
      host: postgres
      port: 5432
      user: airflow
      pass: airflow
      dbname: rss_mining
      schema: dbt

  target: dev

# Used for development via CLI
dbt_transformations:
  outputs:
    dev:
      type: postgres
      threads: 1
      host: localhost
      port: 5432
      user: airflow
      pass: airflow
      dbname: rss_mining
      schema: dbt

  target: dev
